drop table if exists signs_of_life_crawler;
create table signs_of_life_crawler (
    id serial primary key,
    date date default now(),
    filename varchar not null,
    input_url varchar not null,
    final_url varchar not null,
    tld varchar, 
    category varchar, 
    subcategory varchar, 
	language varchar,
    source varchar,
	pred_is_parked varchar,
    ind_non_schema varchar, 
    is_error varchar,
    comment varchar, 
    is_redirected varchar,
    is_redirected_different_domain varchar,
    redirection_type varchar, 
    url_history varchar, 
    all_status_codes varchar, 
    history varchar,
    park_service varchar, 
    kw_park_notice varchar,
    n_letter varchar,
    n_words varchar,
    flag_js_found varchar,
    flag_css varchar,
    document_write varchar,
    flag_iframe varchar,
	ssl_enabled varchar,
    unique(date, filename, input_url)
);
comment on table signs_of_life_crawler is 'signs_of_life_crawler table holds all incoming processed data from the signs of life crawler';
